# Generated by Django 4.2.10 on 2025-03-20 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='讨论区名称')),
                ('description', models.TextField(blank=True, verbose_name='讨论区描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '讨论区',
                'verbose_name_plural': '讨论区',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('code', models.CharField(max_length=20, verbose_name='专业代码')),
                ('degree_type', models.CharField(choices=[('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士'), ('vocational', '专科')], max_length=20, verbose_name='学位类型')),
                ('subject_category', models.CharField(choices=[('philosophy', '哲学'), ('economics', '经济学'), ('law', '法学'), ('education', '教育学'), ('literature', '文学'), ('history', '历史学'), ('science', '理学'), ('engineering', '工学'), ('agriculture', '农学'), ('medicine', '医学'), ('management', '管理学'), ('art', '艺术学')], max_length=20, verbose_name='学科门类')),
                ('description', models.TextField(blank=True, verbose_name='专业描述')),
                ('career_prospects', models.TextField(blank=True, verbose_name='就业前景')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档'), ('deleted', '已删除')], default='published', max_length=20, verbose_name='状态')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='schools.forum')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='院校名称')),
                ('english_name', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='院校代码')),
                ('abbreviation', models.CharField(blank=True, max_length=50, verbose_name='简称')),
                ('school_type', models.CharField(choices=[('comprehensive', '综合类'), ('science', '理工类'), ('agriculture', '农林类'), ('medicine', '医药类'), ('normal', '师范类'), ('language', '语言类'), ('finance', '财经类'), ('political', '政法类'), ('art', '艺术类'), ('sport', '体育类'), ('military', '军事类'), ('other', '其他')], default='comprehensive', max_length=20, verbose_name='院校类型')),
                ('school_level', models.CharField(choices=[('985', '985工程'), ('211', '211工程'), ('double_first_class', '双一流'), ('ordinary', '普通本科'), ('vocational', '高职高专'), ('independent', '独立学院'), ('sino_foreign', '中外合作'), ('other', '其他')], default='ordinary', max_length=20, verbose_name='院校层次')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='创建年份')),
                ('province', models.CharField(max_length=20, verbose_name='所在省份')),
                ('city', models.CharField(max_length=20, verbose_name='所在城市')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='详细地址')),
                ('location', models.CharField(blank=True, help_text='经纬度，格式：纬度,经度', max_length=100, verbose_name='地理坐标')),
                ('website', models.URLField(blank=True, verbose_name='官方网站')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('admission_office_phone', models.CharField(blank=True, max_length=50, verbose_name='招生办电话')),
                ('admission_office_email', models.EmailField(blank=True, max_length=254, verbose_name='招生办邮箱')),
                ('has_graduate_program', models.BooleanField(default=False, verbose_name='是否有研究生院')),
                ('introduction', models.TextField(blank=True, verbose_name='学校简介')),
                ('features', models.TextField(blank=True, verbose_name='特色优势')),
                ('facilities', models.TextField(blank=True, verbose_name='校园设施')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name='校徽')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='schools/banners/', verbose_name='校园图片')),
                ('student_count', models.IntegerField(blank=True, null=True, verbose_name='学生人数')),
                ('faculty_count', models.IntegerField(blank=True, null=True, verbose_name='教师人数')),
                ('national_rank', models.IntegerField(blank=True, null=True, verbose_name='全国排名')),
                ('world_rank', models.IntegerField(blank=True, null=True, verbose_name='世界排名')),
                ('is_verified', models.BooleanField(default=False, verbose_name='信息是否已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '院校',
                'verbose_name_plural': '院校',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('posts', models.ManyToManyField(blank=True, related_name='tags', to='schools.post')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='schools.school'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='schools.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='schools.post')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '院校评分',
                'verbose_name_plural': '院校评分',
                'unique_together': {('school', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SchoolMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在招')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.major')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='schools.school')),
            ],
            options={
                'verbose_name': '院校专业',
                'verbose_name_plural': '院校专业',
                'unique_together': {('school', 'major')},
            },
        ),
        migrations.CreateModel(
            name='MajorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='schools.major')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '专业评分',
                'verbose_name_plural': '专业评分',
                'unique_together': {('major', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('score_type', models.CharField(choices=[('art', '文科'), ('science', '理科'), ('comprehensive', '综合')], max_length=20, verbose_name='科类')),
                ('min_score', models.IntegerField(verbose_name='最低分')),
                ('max_score', models.IntegerField(verbose_name='最高分')),
                ('avg_score', models.IntegerField(verbose_name='平均分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_scores', to='schools.major')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_scores', to='schools.school')),
            ],
            options={
                'verbose_name': '录取分数线',
                'verbose_name_plural': '录取分数线',
                'unique_together': {('school', 'major', 'year', 'province', 'score_type')},
            },
        ),
    ]
