# Generated by Django 6.0.2 on 2026-03-29 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionscore',
            options={'ordering': ['-year'], 'verbose_name': '录取分数线', 'verbose_name_plural': '录取分数线'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name': '论坛', 'verbose_name_plural': '论坛'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_sticky', '-created_at'], 'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-national_rank', 'name'], 'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='schoolmajor',
            options={'verbose_name': '学校专业', 'verbose_name_plural': '学校专业'},
        ),
        migrations.AlterModelOptions(
            name='schoolrating',
            options={'verbose_name': '学校评分', 'verbose_name_plural': '学校评分'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterUniqueTogether(
            name='admissionscore',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='major',
            name='career_prospects',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.RemoveField(
            model_name='school',
            name='admission_office_email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='admission_office_phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='school',
            name='features',
        ),
        migrations.RemoveField(
            model_name='school',
            name='has_graduate_program',
        ),
        migrations.RemoveField(
            model_name='school',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='school',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='world_rank',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.AddField(
            model_name='admissionscore',
            name='ranking',
            field=models.IntegerField(blank=True, null=True, verbose_name='排名'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='是否发布'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_sticky',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_精华',
            field=models.BooleanField(default=False, verbose_name='是否精华'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='schools.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览数'),
        ),
        migrations.AddField(
            model_name='school',
            name='campus_area',
            field=models.FloatField(blank=True, null=True, verbose_name='校园面积(万平方米)'),
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, verbose_name='学校描述'),
        ),
        migrations.AddField(
            model_name='schoolmajor',
            name='is_characteristic_major',
            field=models.BooleanField(default=False, verbose_name='是否特色专业'),
        ),
        migrations.AddField(
            model_name='schoolmajor',
            name='is_key_major',
            field=models.BooleanField(default=False, verbose_name='是否重点专业'),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='admissionscore',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_scores', to='schools.major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='admissionscore',
            name='province',
            field=models.CharField(max_length=50, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='admissionscore',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_scores', to='schools.school', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='admissionscore',
            name='score_type',
            field=models.CharField(choices=[('science', '理科'), ('liberal_arts', '文科'), ('comprehensive', '综合')], max_length=20, verbose_name='科类'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='schools.comment', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='schools.post', verbose_name='帖子'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(blank=True, verbose_name='论坛描述'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=100, verbose_name='论坛名称'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='schools.school', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='major',
            name='degree_type',
            field=models.CharField(choices=[('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], default='bachelor', max_length=20, verbose_name='学位类型'),
        ),
        migrations.AlterField(
            model_name='major',
            name='subject_category',
            field=models.CharField(choices=[('philosophy', '哲学'), ('economics', '经济学'), ('law', '法学'), ('education', '教育学'), ('literature', '文学'), ('history', '历史学'), ('science', '理学'), ('engineering', '工学'), ('agriculture', '农学'), ('medicine', '医学'), ('management', '管理学'), ('art', '艺术学')], default='science', max_length=20, verbose_name='学科门类'),
        ),
        migrations.AlterField(
            model_name='majorrating',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='schools.major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='majorrating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='majorrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_ratings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='schools.forum', verbose_name='论坛'),
        ),
        migrations.AlterField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, verbose_name='简称'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=50, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='学校代码'),
        ),
        migrations.AlterField(
            model_name='school',
            name='faculty_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='教职工人数'),
        ),
        migrations.AlterField(
            model_name='school',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='建校时间'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='school',
            name='province',
            field=models.CharField(max_length=50, verbose_name='所在省份'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_level',
            field=models.CharField(choices=[('985', '985工程'), ('211', '211工程'), ('double_first_class', '双一流'), ('key', '重点'), ('ordinary', '普通')], default='ordinary', max_length=20, verbose_name='办学层次'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('comprehensive', '综合'), ('science', '理工'), ('liberal_arts', '文科'), ('medical', '医药'), ('agriculture', '农林'), ('normal', '师范'), ('finance', '财经'), ('engineering', '工科'), ('other', '其他')], default='comprehensive', max_length=20, verbose_name='学校类型'),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, verbose_name='学校官网'),
        ),
        migrations.AlterField(
            model_name='schoolmajor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否开设'),
        ),
        migrations.AlterField(
            model_name='schoolmajor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='schoolmajor',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='schools.school', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='schoolrating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='schoolrating',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='schools.school', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='schoolrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_ratings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('organizer', models.CharField(max_length=100, verbose_name='组织者')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='活动容量')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='报名截止时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('status', models.CharField(choices=[('upcoming', '即将开始'), ('ongoing', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='upcoming', max_length=20, verbose_name='活动状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.school', verbose_name='学校')),
            ],
            options={
                'verbose_name': '校园活动',
                'verbose_name_plural': '校园活动',
                'ordering': ['start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='admissionscore',
            name='max_score',
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='报名状态')),
                ('metadata', models.JSONField(default=dict, verbose_name='报名信息')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='schools.event', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
