# Generated by Django 6.0.2 on 2026-04-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_admissionscore_options_alter_forum_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='school_images/', verbose_name='学校照片'),
        ),
    ]
