# Generated by Django 6.0.6 on 2026-07-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='school',
        ),
        migrations.RemoveField(
            model_name='post',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
