# Generated by Django 6.0.6 on 2026-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_remove_forum_school_remove_post_forum_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admissionscore',
            index=models.Index(fields=['school', '-year'], name='schools_score_sch_year_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionscore',
            index=models.Index(fields=['province', '-year'], name='schools_score_prov_year_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['school', 'start_time'], name='schools_event_sch_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_time'], name='schools_event_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['province'], name='schools_school_province_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['school_type'], name='schools_school_type_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['school_level'], name='schools_school_level_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['-national_rank'], name='schools_school_rank_idx'),
        ),
    ]
