# Generated by Django 6.0.6 on 2026-07-05 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_admissionscore_schools_score_sch_year_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='地点名称')),
                ('category', models.CharField(choices=[('landmark', '地标'), ('building', '教学楼'), ('dormitory', '宿舍'), ('canteen', '食堂'), ('library', '图书馆'), ('sport', '体育场馆'), ('activity', '活动场所'), ('scenic', '景点'), ('other', '其他')], default='other', max_length=20, verbose_name='地点类型')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('description', models.TextField(blank=True, verbose_name='地点描述')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='详细地址')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标标识')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('checkin_count', models.PositiveIntegerField(default=0, verbose_name='打卡次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='schools.school', verbose_name='所属学校')),
            ],
            options={
                'verbose_name': '校园地点',
                'verbose_name_plural': '校园地点',
                'ordering': ['-checkin_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='打卡时纬度')),
                ('longitude', models.FloatField(verbose_name='打卡时经度')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='打卡备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='schools.place', verbose_name='地点')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['school', 'category'], name='schools_place_sch_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='schools_place_lat_lng_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['user', '-created_at'], name='schools_checkin_user_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['place', '-created_at'], name='schools_checkin_place_crt_idx'),
        ),
    ]
