# Generated by Django 6.0.6 on 2026-07-05 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', '-created_at'], name='content_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['author', 'status'], name='content_author_status_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type', 'status'], name='content_type_status_idx'),
        ),
    ]
