# Generated by Django 6.0.6 on 2026-07-06 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_content_status_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['title'], name='content_title_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', 'title'], name='content_status_title_idx'),
        ),
    ]
