# Generated by Django 6.0.2 on 2026-04-03 05:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='learning.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='课程别名')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='learning/courses/', verbose_name='课程封面')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='课程价格')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('enroll_count', models.IntegerField(default=0, verbose_name='报名人数')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='讲师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('description', models.TextField(blank=True, verbose_name='章节描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='learning.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('progress', models.FloatField(default=0.0, verbose_name='学习进度')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课程报名',
                'verbose_name_plural': '课程报名',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资源标题')),
                ('description', models.TextField(blank=True, verbose_name='资源描述')),
                ('file', models.FileField(upload_to='learning/resources/', verbose_name='资源文件')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('file_size', models.IntegerField(verbose_name='文件大小')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learning.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '学习资源',
                'verbose_name_plural': '学习资源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课时标题')),
                ('description', models.TextField(blank=True, verbose_name='课时描述')),
                ('content', models.TextField(blank=True, verbose_name='课时内容')),
                ('video_url', models.URLField(blank=True, verbose_name='视频链接')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='时长')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('view_count', models.IntegerField(default=0, verbose_name='观看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.chapter', verbose_name='章节')),
            ],
            options={
                'verbose_name': '课时',
                'verbose_name_plural': '课时',
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='learning.category', verbose_name='分类')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='learning.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程分类关联',
                'verbose_name_plural': '课程分类关联',
                'unique_together': {('course', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('last_watched_at', models.DateTimeField(blank=True, null=True, verbose_name='最后观看时间')),
                ('watched_duration', models.DurationField(default=datetime.timedelta(0), verbose_name='观看时长')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='learning.enrollment', verbose_name='报名')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='learning.lesson', verbose_name='课时')),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度',
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评价内容')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否批准')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课程评价',
                'verbose_name_plural': '课程评价',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
