# Generated by Django 6.0.6 on 2026-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='last_position',
            field=models.IntegerField(default=0, verbose_name='上次观看位置(秒)'),
        ),
    ]
