# Generated by Django 6.0.6 on 2026-07-05 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_progress_last_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'is_published'], name='learn_course_inst_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', '-created_at'], name='learn_course_pub_crt_idx'),
        ),
    ]
