# Generated by Django 6.0.2 on 2026-03-29 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_admissionscore_options_alter_forum_options_and_more'),
        ('users', '0003_user_favorite_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='横幅'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_schools',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('browse', '浏览'), ('search', '搜索'), ('favorite', '收藏'), ('compare', '对比'), ('rate', '评分')], max_length=50, verbose_name='行为类型')),
                ('target_type', models.CharField(choices=[('school', '院校'), ('major', '专业'), ('post', '帖子'), ('topic', '主题')], max_length=50, verbose_name='目标类型')),
                ('target_id', models.IntegerField(verbose_name='目标ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'ordering': ['-timestamp'],
            },
        ),
    ]
