# Generated by Django 4.2.10 on 2025-04-01 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_board_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('flagged', '标记审查')], default='approved', max_length=20, verbose_name='内容状态'),
        ),
        migrations.AddField(
            model_name='post',
            name='review_note',
            field=models.TextField(blank=True, null=True, verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
