# Generated by Django 6.0.6 on 2026-07-05 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_comment_commentlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', '-created_at'], name='forum_bmk_user_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='forum_cmt_post_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='forum_cmt_author_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='forum_notif_user_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='forum_notif_user_read_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['topic', 'created_at'], name='forum_post_topic_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_at'], name='forum_post_author_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content_status', 'created_at'], name='forum_post_status_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['board', '-created_at'], name='forum_topic_board_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['author', '-created_at'], name='forum_topic_author_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['status', '-created_at'], name='forum_topic_status_crt_idx'),
        ),
    ]
