# Generated by Django 6.0.6 on 2026-07-06 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_bookmark_forum_bmk_user_crt_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['topic', 'content_status', 'created_at'], name='forum_post_topic_status_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['title'], name='forum_topic_title_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['board', 'status', '-created_at'], name='forum_topic_board_status_crt_idx'),
        ),
    ]
