# Generated by Django 6.0.6 on 2026-07-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post_forum_post_topic_status_crt_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='forum_post_topic_st_crt_idx',
            old_name='forum_post_topic_status_crt_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='forum_topic_brd_st_crt_idx',
            old_name='forum_topic_board_status_crt_idx',
        ),
    ]
