# Generated by Django 5.1.7 on 2025-03-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0002_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_schools',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='schools.school', verbose_name='收藏的学校'),
        ),
    ]
