# Generated by Django 6.0.2 on 2026-05-26 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_activity_activitycomment_message_activitylike_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', '注册'), ('login', '登录'), ('post', '发帖'), ('reply', '回复'), ('like', '点赞'), ('comment', '评论'), ('share', '分享'), ('invite', '邀请'), ('daily_checkin', '每日签到'), ('complete_profile', '完善资料'), ('verified', '身份认证'), ('system', '系统奖励'), ('admin', '管理员操作')], max_length=50, verbose_name='行为类型')),
                ('points', models.IntegerField(verbose_name='积分变化')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
