# Generated by Django 6.0.2 on 2026-07-02 13:58

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='users_messa_sender__f013b9_idx',
            old_name='users_messag_sender__6c4c50_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='users_messa_receive_a27d12_idx',
            old_name='users_messag_receive_3e2c3e_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[users.validators.validate_image_extension, users.validators.validate_avatar_size], verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[users.validators.validate_image_extension, users.validators.validate_banner_size], verbose_name='横幅'),
        ),
    ]
