# Generated by Django 6.0.6 on 2026-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_users_messag_sender__6c4c50_idx_users_messa_sender__f013b9_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pointsrecord',
            index=models.Index(fields=['user', 'action', '-created_at'], name='users_pts_user_act_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsrecord',
            index=models.Index(fields=['user', '-created_at'], name='users_pts_user_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type', '-timestamp'], name='users_act_user_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['target_type', 'target_id'], name='users_act_target_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['email', 'is_used', 'code_type'], name='users_code_email_used_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['phone', 'is_used', 'code_type'], name='users_code_phone_used_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['created_at'], name='users_code_created_idx'),
        ),
    ]
